/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManufacturerRole;

import Business.Enterprise.Enterprise;
import Business.Inventory.Catalog;
import Business.Inventory.HospitalInventory;
import Business.Inventory.Category;
import Business.Inventory.Item;
import Business.Inventory.ManufactureInventory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sutha
 */
public class AddItemsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
  //  private HospitalInventory catalogdir;
    private ManufactureInventory manuDir;

    /**
     * Creates new form AddItemsJPanel
     */
    public AddItemsJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, ManufactureInventory manuDir) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.manuDir = manuDir;
        valueLabel.setText(enterprise.getEnterpriseType() + "-" + enterprise.getName());
        nameLabel.setText(userAccount.getUsername());
        buttonGroup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        quantityTxtField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        addItemBtn = new javax.swing.JButton();
        itemTxtField1 = new javax.swing.JTextField();
        categoryTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        drugRadioButton = new javax.swing.JRadioButton();
        surgicalRadioButton = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Catalog");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jLabel1.setText("Category");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        jLabel4.setText("Item");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jLabel2.setText("Quantity");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));

        quantityTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTxtFieldActionPerformed(evt);
            }
        });
        add(quantityTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 89, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 400, 90, -1));

        addItemBtn.setText("Add item");
        addItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemBtnActionPerformed(evt);
            }
        });
        add(addItemBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 100, -1));
        add(itemTxtField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 89, -1));
        add(categoryTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 89, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/ManufacturerRole/images/Manufacturer.jpeg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 200, 230));

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameLabel.setText("<Name Label>");
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 410, 30));

        drugRadioButton.setText("Drugs");
        add(drugRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        surgicalRadioButton.setText("Surgical Item");
        add(surgicalRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        jPanel1.setBackground(new java.awt.Color(110, 89, 222));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        jPanel1.add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 120, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        valueLabel.setText("<value>");
        jPanel1.add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 310, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1770, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void quantityTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTxtFieldActionPerformed

    private void buttonGroup() {
        ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(drugRadioButton);
        buttonGroup.add(surgicalRadioButton);
    }

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageInventoryJPanel mijp = (ManageInventoryJPanel) component;
        mijp.populateItems();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void addItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemBtnActionPerformed
        int quantity = 0;
        boolean flag = false;

        if (drugRadioButton.isSelected() == true) {
            if (categoryTxtField.getText().isEmpty() == true || itemTxtField1.getText().isEmpty() == true || quantityTxtField.getText().isEmpty() == true) {
                JOptionPane.showMessageDialog(null, "Enter all the value first");
            } else {
                try {
                    String catalogName = drugRadioButton.getText();
                    String categoryName = categoryTxtField.getText();
                    String itemName = itemTxtField1.getText();

                    quantity = Integer.parseInt(quantityTxtField.getText());

                    Catalog catalog = manuDir.addCatalog(catalogName);
                    Category category = catalog.addCategory(categoryName);
                    Item item = category.addItem(itemName, quantity);
                    flag = true;
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Only Numbers allowed in Quantity");
                }
            }
        } else if (surgicalRadioButton.isSelected() == true) {

            if (categoryTxtField.getText().isEmpty() == true || itemTxtField1.getText().isEmpty() == true || quantityTxtField.getText().isEmpty() == true) {
                JOptionPane.showMessageDialog(null, "Enter all the value first");
            } else {
                try {
                    String catalogName = surgicalRadioButton.getText();
                    String categoryName = categoryTxtField.getText();
                    String itemName = itemTxtField1.getText();

                    quantity = Integer.parseInt(quantityTxtField.getText());

                    Catalog catalog = manuDir.addCatalog(catalogName);
                    Category category = catalog.addCategory(categoryName);
                    Item item = category.addItem(itemName, quantity);
                    flag = true;
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Only Numbers allowed in Quantity");

                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select catalog Radio box!");
        }
        if (flag == true) {
            JOptionPane.showMessageDialog(null, "Items successfully Added to Inventory");
        }
        drugRadioButton.setSelected(false);
        surgicalRadioButton.setSelected(false);
        categoryTxtField.setText("");
        itemTxtField1.setText("");
        quantityTxtField.setText("");
    }//GEN-LAST:event_addItemBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemBtn;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField categoryTxtField;
    private javax.swing.JRadioButton drugRadioButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JTextField itemTxtField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField quantityTxtField;
    private javax.swing.JRadioButton surgicalRadioButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
