/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.Hospital.DoctorRole;

import Business.Enterprise.Enterprise;
import Business.HospitalEnterprise.Organization.ProcurementOrganization;
import Business.Organization.Organization;
import Business.Inventory.Catalog;
import Business.Inventory.HospitalInventory;
import Business.Inventory.Category;
import Business.Inventory.Item;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DoctorOrderRequest;
import UserInterface.Hospital.DoctorRole.DoctorWorkAreaJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sutha
 */
public class RequestItemJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestOrderJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private HospitalInventory catDir;

    public RequestItemJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, HospitalInventory catDir) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.catDir = catDir;
        valueLabel.setText(enterprise.getEnterpriseType() + "-" + enterprise.getName());
        nameLabel.setText(userAccount.getUsername());
        popCatalogComboBox();
        popPriorityComboBox();
    }

       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        quantityTxtField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        requestTestJButton = new javax.swing.JButton();
        CategoryComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        catalogComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        itemComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        priorityComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Category");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        quantityTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTxtFieldActionPerformed(evt);
            }
        });
        add(quantityTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 89, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        requestTestJButton.setText("Request item");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, -1));

        CategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(CategoryComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 90, -1));

        jLabel2.setText("Quantity");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, -1));

        jLabel3.setText("Catalog");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        catalogComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        catalogComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogComboBoxActionPerformed(evt);
            }
        });
        add(catalogComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 90, -1));

        jLabel4.setText("Item");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameLabel.setText("<Name Label>");
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 510, 30));

        itemComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(itemComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 90, -1));

        jLabel6.setText("Priority");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));

        priorityComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        priorityComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priorityComboBoxActionPerformed(evt);
            }
        });
        add(priorityComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 90, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Hospital/DoctorRole/images/doctor.jpg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 210, 190));

        jPanel1.setBackground(new java.awt.Color(110, 89, 222));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        jPanel1.add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 120, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        valueLabel.setText("<value>");
        jPanel1.add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 410, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1770, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorWorkAreaJPanel dwjp = (DoctorWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        
        if(quantityTxtField.getText().isEmpty() == true){
            JOptionPane.showMessageDialog(null, "Please fill out all details");
        }
        else{
         try{
        String catalog = (String) catalogComboBox.getSelectedItem();
        String category = (String) CategoryComboBox.getSelectedItem();
        String item = (String) itemComboBox.getSelectedItem();
        String priority = (String) priorityComboBox.getSelectedItem();
        int quantity = Integer.parseInt(quantityTxtField.getText());
        DoctorOrderRequest request = new DoctorOrderRequest();
        request.setCatalog(catalog);
        request.setCategory(category);
        request.setItem(item);
        request.setPriority(priority);
        request.setQuantity(quantity);
        request.setSender(userAccount);
        request.setStatus("Request Initiated");
        request.setRequestDate(new Date());
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof ProcurementOrganization) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
         }
         catch(NumberFormatException e){
             JOptionPane.showMessageDialog(null, "Please enter details in Correct Format");
             return;
         }
        JOptionPane.showMessageDialog(null,"Request sent to Procurement Team");
        }
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void quantityTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTxtFieldActionPerformed

    private void catalogComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catalogComboBoxActionPerformed

    private void priorityComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priorityComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priorityComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CategoryComboBox;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox catalogComboBox;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JComboBox itemComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JComboBox priorityComboBox;
    private javax.swing.JTextField quantityTxtField;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables

    private void popCatalogComboBox() {
        catalogComboBox.removeAllItems();
        CategoryComboBox.removeAllItems();
        itemComboBox.removeAllItems();
        for (Catalog catalog : catDir.getCatalogDir()) {
            catalogComboBox.addItem(catalog.getCatalogName());
            popCategory(catalog);
        }
    }

    private void popCategory(Catalog catlog) {
        for (Category category : catlog.getCategoryDir()) {
            CategoryComboBox.addItem(category.getCategoryName());
            popItem(category);
        }
    }

    private void popItem(Category category) {
        for (Item item : category.getItemDir()) {
            itemComboBox.addItem(item.getName());
        }
    }
    
    private void popPriorityComboBox() {
        priorityComboBox.removeAllItems();
        priorityComboBox.addItem("Low");
        priorityComboBox.addItem("Medium");
        priorityComboBox.addItem("High");
    }
}
