/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SupplierRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.ManufactureEnterprise;
import Business.Inventory.HospitalInventory;
import Business.ManufacturerEnterprise.Organization.ManufacturerOrganization;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krina Thakkar
 */
public class ManageOrderWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private HospitalInventory catDir;
    private WorkRequest request;

    /**
     * Creates new form ManageOrderWorkAreaJPanel
     */
    public ManageOrderWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, EcoSystem business, HospitalInventory catDir, WorkRequest request) {
        initComponents();
        this.system = business;
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.catDir = catDir;
        this.request = request;
        valueLabel.setText(enterprise.getEnterpriseType() + "-" + enterprise.getName());
        nameLabel.setText(userAccount.getUsername());
        populateData();
        populateSupplierOrderTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manufacturerComboBox = new javax.swing.JComboBox();
        sendOrderBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        networkComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        itemTextField = new javax.swing.JTextField();
        quantityTextField = new javax.swing.JTextField();
        priorityTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        supplierWorkRequestJTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manufacturerComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(manufacturerComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 80, -1));

        sendOrderBtn.setText("Send Order");
        sendOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendOrderBtnActionPerformed(evt);
            }
        });

        add(sendOrderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, -1));

        jLabel1.setText("Item");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel2.setText("Quantity");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel3.setText("Priority");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jLabel4.setText("Select Network");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        networkComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(networkComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 80, -1));

        jLabel5.setText("Select Manufacturer");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));
        add(itemTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 80, -1));
        add(quantityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 80, -1));

        priorityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priorityTextFieldActionPerformed(evt);
            }
        });
        add(priorityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 80, -1));

        supplierWorkRequestJTable.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        supplierWorkRequestJTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        supplierWorkRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity", "Priority", "Sender", "Receiver", "Status", "Request Date", "Resolve Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        supplierWorkRequestJTable.setRequestFocusEnabled(false);
        supplierWorkRequestJTable.setRowHeight(25);
        supplierWorkRequestJTable.setRowMargin(5);
        supplierWorkRequestJTable.setSelectionBackground(new java.awt.Color(110, 89, 222));
        jScrollPane1.setViewportView(supplierWorkRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 750, 130));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Orders to Manufacturer");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 240, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/SupplierRole/images/supplier.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 80, 180, 200));

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameLabel.setText("<Name Label>");
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 330, 390, 30));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));

        jPanel1.setBackground(new java.awt.Color(110, 89, 222));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        jPanel1.add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 120, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        valueLabel.setText("<value>");
        jPanel1.add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 320, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1770, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void sendOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendOrderBtnActionPerformed
        String network = networkComboBox.getSelectedItem().toString();
        String enterprise = manufacturerComboBox.getSelectedItem().toString();
        request.setSender(userAccount);
        request.setStatus("Sent to Manfucture");
        Organization org = null;
        for (Network n : system.getNetworkList()) {
            if (n.getName().equalsIgnoreCase(network)) {

                for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                    if (e.getName().equalsIgnoreCase(enterprise)) {
                        for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                            if (o instanceof ManufacturerOrganization) {
                                org = o;
                            }
                        }
                    }
                }
            }
        }

        if (org != null) {
            userAccount.getWorkQueue().getWorkRequestList().add(request);
            org.getWorkQueue().getWorkRequestList().add(request);
            populateSupplierOrderTable();
        }

        JOptionPane.showMessageDialog(null, "Request sent successfully");

    }//GEN-LAST:event_sendOrderBtnActionPerformed

    private void priorityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priorityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priorityTextFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SupplierWorkAreaJPanel swjp = (SupplierWorkAreaJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed
    public void populateData() {
        itemTextField.setText(request.getItem());
        quantityTextField.setText(String.valueOf(request.getQuantity()));
        priorityTextField.setText(request.getPriority());
        networkComboBox.removeAllItems();
        for (Network network : system.getNetworkList()) {
            networkComboBox.addItem(network);
            manufacturerComboBox.removeAllItems();
            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (e instanceof ManufactureEnterprise) {
                    manufacturerComboBox.addItem(e);
                }

            }
        }
        
         for (Network network : system.getNetworkList()) {
            networkComboBox.addItem(network);
            manufacturerComboBox.removeAllItems();
            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (e instanceof ManufactureEnterprise) {
                    manufacturerComboBox.addItem(e);
                }

            }
        }
        
        
    }

    public void populateSupplierOrderTable() {
        DefaultTableModel model = (DefaultTableModel) supplierWorkRequestJTable.getModel();

        model.setRowCount(0);
        System.out.println("In Table");
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[8];
            row[0] = request.getItem();
            row[1] = request.getQuantity();
            row[2] = request.getPriority();
            row[3] = request.getSender();
            row[4] = request.getReceiver();
            row[5] = request.getStatus();
            DateFormat dateformat = new SimpleDateFormat("MM/dd/yyyy");
            row[6] = dateformat.format(request.getRequestDate());
            if (request.getResolveDate() != null) {
                row[7] = dateformat.format(request.getResolveDate());
            } else {
                row[7] = "";
            }
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable SupplierWorkRequestJTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JTextField itemTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox manufacturerComboBox;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JComboBox networkComboBox;
    private javax.swing.JTextField priorityTextField;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JButton sendOrderBtn;
    private javax.swing.JTable supplierWorkRequestJTable;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
