/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital.ProcurementRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.HospitalEnterprise.Organization.ProcurementOrganization;
import Business.Inventory.Catalog;
import Business.Inventory.Category;
import Business.Inventory.HospitalInventory;
import Business.Inventory.Item;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sutha
 */
public class ManageOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrderJPanel
     */
    private JPanel userProcessContainer;
    private ProcurementOrganization procurementOrganization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private HospitalInventory catDir;
    private EcoSystem business;

    public ManageOrderJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, HospitalInventory catDir, EcoSystem business) {
        initComponents();
        this.catDir = catDir;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        valueLabel.setText(enterprise.getName());
        nameLabel.setText(userAccount.getUsername());
        populateProcurementOrders();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        supplierRequestBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        procurementWorkRequestJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        supplierRequestBtn.setText("Request New Order");
        supplierRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierRequestBtnActionPerformed(evt);
            }
        });
        add(supplierRequestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Procurement Team Orders to Suppliers");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        procurementWorkRequestJTable.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        procurementWorkRequestJTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        procurementWorkRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity", "Priority", "Sender", "Receiver", "Status", "Request Date", "Resolve Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        procurementWorkRequestJTable.setCellSelectionEnabled(true);
        procurementWorkRequestJTable.setRowHeight(25);
        procurementWorkRequestJTable.setRowMargin(5);
        procurementWorkRequestJTable.setSelectionBackground(new java.awt.Color(110, 89, 222));
        jScrollPane1.setViewportView(procurementWorkRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 970, 97));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 110, 30));

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameLabel.setText("<Name Label>");
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 340, 390, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Hospital/ProcurementRole/images/procurement.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 100, 190, -1));

        jPanel1.setBackground(new java.awt.Color(110, 89, 222));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        jPanel1.add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 127, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        valueLabel.setText("<value>");
        jPanel1.add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 320, 26));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1840, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void supplierRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierRequestBtnActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("OrderJPanel", new OrderJPanel(userProcessContainer, userAccount, enterprise, catDir, business));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_supplierRequestBtnActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ProcurementWorkAreaJPanel pwjp = (ProcurementWorkAreaJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    public void populateProcurementOrders() {
        DefaultTableModel model = (DefaultTableModel) procurementWorkRequestJTable.getModel();
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[8];
            row[0] = request;
            row[1] = request.getQuantity();
            row[2] = request.getPriority();
            row[3] = request.getSender();
            row[4] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[5] = request.getStatus();
            DateFormat dateformat = new SimpleDateFormat("MM/dd/yyyy");
            row[6] = dateformat.format(request.getRequestDate());
            if (request.getResolveDate() != null) {
                row[7] = dateformat.format(request.getResolveDate());
            } else {
                row[7] = "";
            }
            model.addRow(row);

            if (request.getStatus().equalsIgnoreCase("Completed")) {
                updateInventory(request);
            }
        }
    }

    public void updateInventory(WorkRequest request) {
        String catalog = request.getCatalog();
        //System.out.println(catalog);
        String category = request.getCategory();
        //System.out.println(category);
        String item = request.getItem();
        //System.out.println(item);
        int quantity = request.getQuantity();
        //System.out.println(quantity);
        for (Catalog c : catDir.getCatalogDir()) {
            for (Category cat : c.getCategoryDir()) {
                for (Item i : cat.getItemDir()) {
                    if (c.getCatalogName().equalsIgnoreCase(catalog) && cat.getCategoryName().equalsIgnoreCase(category) && i.getName().equalsIgnoreCase(item)) {

                        i.setQuantity(i.getQuantity() + quantity);
                    }
                }
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTable procurementWorkRequestJTable;
    private javax.swing.JButton supplierRequestBtn;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
